static const char *DefaultLanguageStringTable[SYS_UI_MSG_COUNT]={
	"System initialization error.",
	"Proceed?",
	"Cancel input?",
	"Please fill the full game title!",
	"Please fill OSD title 1!",
	"Change game icon?",
	"Unable to load selected icon. Continue with default icon?",
	"Failed to install OSD files.",
	"No harddisk drive was detected.",
	"Harddisk drive not formatted. Format?\nWarning: All data will be erased.",
	"Quit program?",
	"Game updated successfully!",
	"An error occurred while updating the game.",
	"Delete game?",
	"Please wait...",
	"This game was already installed.\nOverwrite old installation?",
	"Game installed successfully!",
	"Unsupported disc inserted.\nPlease insert a Playstation 2 game disc.",
	"Please insert a disc.",
	"Reading disc...",
	"An error occurred while reading the disc.",
	"An error occurred while parsing SYSTEM.CNF.\nPlease insert another disc.",
	"Cancel game installation?",
	"A read fault occurred.\nPlease check the condition of your disc.",
	"A write fault occurred.\nPlease send your disk for repair.",
	"Lack of memory.\nPlease restart the installer.",
	"Game installation canceled.",
	"Failed to access partition.",
	"A computer is connected to this console.\n\nPlease do not disconnect or switch off the console.",
	"No icons found.",
	"Error: there is no network connection.",
	"Connecting to network. Please wait.",
	"Error: failed to acquire an IP address from the DHCP server.",
	"There is insufficient space on the HardDisk Drive (HDD) unit.",
	"Saving. Please do not switch off or disconnect your console.",
	"Error: failed to save settings.",
};

static const char *DefaultLanguageLabelStringTable[SYS_UI_LBL_COUNT]={
	"OK",
	"Cancel",
	"Yes",
	"No",
	"Next",
	"Back",
	"Enabled",
	"Disabled",
	"Toggle option",
	"Select field",
	"Select game",
	"Game options",
	"Delete game",
	"Install game",
	"Select key",
	"Move cursor",
	"Toggle keyboard",
	"Enter",
	"Backspace",
	"Insert space",
	"Quit program",
	"Select icon",
	"Select device",
	"Warning",
	"Error",
	"Information",
	"Confirmation",
	"Please wait",
	"Remote administration mode",
	"Icon source:",
	"Now installing...",
	"Title:",
	"Disc ID:",
	"Disc type:",
	"Rate:",
	"Time\nremaining:",
	"Full title (Max 80 characters):",
	"OSD title line 1 (Max 16 characters):",
	"OSD title line 2 (Max 16 characters):",
	"Accurate reading:",
	"Synchronous reading:",
	"Unhook syscalls:",
	"Disable PSS videos:",
	"Emulate DVD9 support:",
	"Disable IGR:",
	"Unused:",
	"Hide DEV9 module:",
	"Use MWDMA0:",
	"Memory card",
	"Slot 1",
	"Slot 2",
	"USB mass storage",
	"Default",
	"Game save",
	"External icon",
	"Network Status",
	"MAC Address",
	"IP Address",
	"Netmask",
	"Gateway",
	"Link State",
	"Link Mode",
	"Up",
	"Down",
	"Unknown",
	"10Mbps HDX",
	"10Mbps FDX",
	"100Mbps HDX",
	"100Mbps FDX",
	"Flow-Control",
	"Dropped Tx Frames",
	"Dropped Rx Frames",
	"Tx LOSSCR",
	"Rx Overrun",
	"Tx EDEFER",
	"Rx Bad Length",
	"Tx Collision",
	"Rx Bad FCS",
	"Tx Underrun",
	"Rx Bad Alignment",
	"Auto Negotiation",
	"Options",
	"Network Options",
	"Advanced Settings",
	"Use DHCP",
	"Address Type",
	"Sort Titles",
	"Static",
	"DHCP",
};
